// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmccXNCKPSZcIuRWOSQbWfr1fnnJdvPs',
    appId: '1:461240250333:web:9e4141df0ec83f83701034',
    messagingSenderId: '461240250333',
    projectId: 'take-home-d2ce3',
    authDomain: 'take-home-d2ce3.firebaseapp.com',
    storageBucket: 'take-home-d2ce3.appspot.com',
    measurementId: 'G-5ZC4FP2J66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCgeTBYySXSBmogn7R0uolne0vN2KLyBc',
    appId: '1:461240250333:android:2cfaae15ae0628ea701034',
    messagingSenderId: '461240250333',
    projectId: 'take-home-d2ce3',
    storageBucket: 'take-home-d2ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoPjSdaEZwQb14ZiJb44Pgn-58Y6uiRHU',
    appId: '1:461240250333:ios:dfa3624a54784971701034',
    messagingSenderId: '461240250333',
    projectId: 'take-home-d2ce3',
    storageBucket: 'take-home-d2ce3.appspot.com',
    androidClientId: '461240250333-emsd6omh6h1jui4gm20ta6gvnkkee7sm.apps.googleusercontent.com',
    iosBundleId: 'szk.challenge.fanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoPjSdaEZwQb14ZiJb44Pgn-58Y6uiRHU',
    appId: '1:461240250333:ios:57aaf6189584ba25701034',
    messagingSenderId: '461240250333',
    projectId: 'take-home-d2ce3',
    storageBucket: 'take-home-d2ce3.appspot.com',
    androidClientId: '461240250333-emsd6omh6h1jui4gm20ta6gvnkkee7sm.apps.googleusercontent.com',
    iosBundleId: 'szk.challenge.fanFlutter.RunnerTests',
  );
}
